services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - src.parse
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
