services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - src.index
      - --qdrant_host=http://qdrant:6333
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant-storage:/qdrant/storage

volumes:
  qdrant-storage:
